<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="USMUMSDALVE1" failures="1" tests="9" name="tests.testPagesDemo2" time="1.048" errors="0" timestamp="2024-01-05T15:53:46 IST" skipped="6">
  <testcase classname="tests.testPagesDemo2" name="testLoginLink" time="0.551">
    <system-out>
      <![CDATA[test success -> testLoginLink]]>
    </system-out>
  </testcase> <!-- testLoginLink -->
  <testcase classname="tests.testPagesDemo2" name="testRegisterLink" time="0.484">
    <system-out>
      <![CDATA[test success -> testRegisterLink]]>
    </system-out>
  </testcase> <!-- testRegisterLink -->
  <testcase classname="tests.testPagesDemo2" name="testRegisterWithValidUsers" time="0.000">
    <skipped/>
    <system-out>
      <![CDATA[test skipped -> testRegisterWithValidUsers]]>
    </system-out>
  </testcase> <!-- testRegisterWithValidUsers -->
  <testcase classname="tests.testPagesDemo2" name="testRegisterWithValidUsers" time="0.000">
    <skipped/>
    <system-out>
      <![CDATA[test skipped -> testRegisterWithValidUsers]]>
    </system-out>
  </testcase> <!-- testRegisterWithValidUsers -->
  <testcase classname="tests.testPagesDemo2" name="testRegisterWithValidUsers" time="0.000">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at tests.testPagesDemo2.testRegisterWithValidUsers(testPagesDemo2.java:67)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </failure>
    <system-out>
      <![CDATA[test fail -> testRegisterWithValidUsers
Message : expected [true] but found [false]]]>
    </system-out>
  </testcase> <!-- testRegisterWithValidUsers -->
  <testcase classname="tests.testPagesDemo2" name="testRegisterWithValidUsers" time="0.009">
    <skipped/>
    <system-out>
      <![CDATA[test skipped -> testRegisterWithValidUsers]]>
    </system-out>
  </testcase> <!-- testRegisterWithValidUsers -->
  <testcase classname="tests.testPagesDemo2" name="testRegisterWithValidUsers" time="0.001">
    <skipped/>
    <system-out>
      <![CDATA[test skipped -> testRegisterWithValidUsers]]>
    </system-out>
  </testcase> <!-- testRegisterWithValidUsers -->
  <testcase classname="tests.testPagesDemo2" name="testRegisterWithValidUsers" time="0.001">
    <skipped/>
    <system-out>
      <![CDATA[test skipped -> testRegisterWithValidUsers]]>
    </system-out>
  </testcase> <!-- testRegisterWithValidUsers -->
  <testcase classname="tests.testPagesDemo2" name="testLoginWithValidUsers" time="0.002">
    <skipped/>
    <system-out>
      <![CDATA[test skipped -> testLoginWithValidUsers]]>
    </system-out>
  </testcase> <!-- testLoginWithValidUsers -->
  <system-out>
    <![CDATA[test success -> navigateTest
test success -> scrollDemo
test success -> testLoginLink
test success -> testRegisterLink
test skipped -> testRegisterWithValidUsers
test skipped -> testRegisterWithValidUsers
test skipped -> testRegisterWithValidUsers
test skipped -> testRegisterWithValidUsers
test skipped -> testRegisterWithValidUsers
test fail -> testRegisterWithValidUsers
Message : expected [true] but found [false]
test skipped -> testLoginWithValidUsers]]>
  </system-out>
</testsuite> <!-- tests.testPagesDemo2 -->
